### PR TITLE
Only require tslint once

### LINKED ISSUE #65: Incorrect no-shadow-variable failures when using mockTypeScriptVersion
With 0.9.9 released, I've finally got around to replacing my [local workaround](https://github.com/angelozerr/tslint-language-service/issues/58#issuecomment-356962489) for #58 with the proper fix - turning on `mockTypeScriptVersion`.

Unfortunately this results in almost every variable being incorrectly flagged as failing the `no-shadow-variable` rule. That's ~58000 errors in the project I'm working on. This is something I didn't see when testing the original PR, so I'm not sure what's changed.

To reproduce:

* Set up `tslint-language-service` in *Visual Studio 2017* with *TypeScript Tools for Microsoft Visual Studio* installed
* Make sure the typescript version in the project's node_modules is different to the one included in the VS TypeScript Tooling
* Turn on the `mockTypeScriptVersion` option in the plugin
* Open a TS file in VS

This should result in most variables (especially any imports or exports) being flagged as shadowing themselves.

It looks like this is caused by loading tslint twice (`require` then `mockRequire.reRequire`), though I'm not sure why this is the case.

### PR DESCRIPTION
**Pull request by andyrooger**
Fixes #65

This pushes the initial require for tslint to much later in the plugin.
When `mockTypeScriptVersion` is turned on this means we require after mocking typescript, rather than requiring once, and then reRequiring after mocking.

There's an `import * as tslint from 'tslint'` at the top of the file still, but this is currently removed on compilation.

### CODE REVIEW

**Comment by angelozerr** [comment]
@egamma what do you think about this PR?

File: src/index.ts [hunk 1]
```diff
@@ -67,8 +66,8 @@ function init(modules: { typescript: typeof ts_module }) {
 
         if(config.mockTypeScriptVersion) {
             mockRequire('typescript', ts);
-            tslint = mockRequire.reRequire('tslint');
         }
+        const tslint = require('tslint')
```
Comment (egamma) [inline src/index.ts:70]: Couldn´t this be done with the TS support for dynamic imports? https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html see the section on dynamic import expressions.

Comment (andyrooger) [reply src/index.ts:70]: @egamma I just tried this quickly - it seems to have a knock on effect, in that `create()` has to become async to use it. I'm not sure how much else this will affect.

Comment (egamma) [reply src/index.ts:70]: @andyrooger since the code does not rely on typechecking using a require is fine.

Just to confirm, you have tested that this change has no effect when `mockTypeScriptVersion` is false?

Comment (andyrooger) [reply src/index.ts:70]: @egamma Yep. In my case, using Visual Studio Enterprise:

* `mockTypeScriptVersion: true` => Everything works perfectly, lint errors appear in the IDE as they should
* `mockTypeScriptVersion: false` => The wrong version of typescript is loaded successfully, resulting in lots of bizarre lint errors appearing for things they shouldn't. This is exactly how it works for me in 0.9.8 or 0.9.9 without this PR (and with mockTypeScriptVersion turned off).

In both cases I do see linter errors in the IDE, so I presume the packages have at least loaded successfully.

**Comment by andyrooger** [comment]
@angelozerr @egamma Is there anything else that either of you think I need to do/change/test for this PR?

**Comment by egamma** [comment]
LGTM me thanks 👍

**Comment by angelozerr** [comment]
Thanks guys!
